"""buat table categories

Revision ID: 7872ef834939
Revises: f41180c7c732
Create Date: 2022-01-10 14:43:47.701500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7872ef834939'
down_revision = 'f41180c7c732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    # ### end Alembic commands ###
